# Generated by Django 5.2.4 on 2025-08-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
    ]
